# Generated by Django 4.1.7 on 2023-04-02 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0005_userimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
