# Generated by Django 4.1.7 on 2023-04-08 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0007_rename_userimages_userphoto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPhoto',
            new_name='Photo',
        ),
    ]
