# Generated by Django 4.1.7 on 2023-06-28 20:51

import django.core.validators
from django.db import migrations, models
import utils.file_uploader


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0015_alter_like_photo_alter_like_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=utils.file_uploader.uploaded_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg'])]),
        ),
    ]
