# Generated by Django 4.1.7 on 2023-07-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0016_alter_photo_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='likes',
        ),
        migrations.AlterModelTable(
            name='photo',
            table='photos',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
    ]
